// <auto-generated>
//   由 `Adaptor.CsClass` 生成（`lib/adaptor.rav`）—— 别手改，下次生成会盖掉。
//   要改行为：改那张映射表；要改这一份：把它挪出 Ravel.Generated/ 自己接着写。
//
//   类型 System.DateTime → 模块 NDate / 类 DateTime；成员 Add AddDays AddHours AddMicroseconds AddMilliseconds AddMinutes AddMonths AddSeconds AddTicks AddYears CompareTo Deconstruct Equals GetDateTimeFormats GetHashCode GetType GetTypeCode IsDaylightSavingTime Subtract ToBinary ToFileTime ToFileTimeUtc ToLocalTime ToLongDateString ToLongTimeString ToOADate ToShortDateString ToShortTimeString ToString ToUniversalTime TryFormat
//
//   **这是实例那半**：`[ClassCtor]` + `[ClassMethod]`，`self` 先脱壳再调。
//   静态成员在另一份里（`Adaptor.Cs`）。**属性访问器（`get_X` / `set_X`）这一版不做。**
// </auto-generated>

namespace Ravel.Runtime;

[RavelModule("NDate")]
[RavelClass("DateTime", Implements = "IValue")]
internal static class DateTimeAdaptor
{
    private static System.DateTime Me (RuntimeValue self)
        => (System.DateTime)((DotNetVal)self).Value;

    [ClassCtor]
    public static RuntimeValue New (RuntimeValue arg)
        => new DotNetVal (new System.DateTime (PluginKit.Long (arg, "DateTime 的构造器参数")), PluginKit.ClassOf ("DateTime"));

    // 跳过 Add：挑中的那个签名是 TimeSpan -> DateTime，里面有映射表没有的类型（同名 1 个 / 实例 1 个）

    [ClassMethod("AddDays")]
    public static RuntimeValue AddDays (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddDays", () => new DotNetVal (Me (self).AddDays (PluginKit.Num (x0, "NDate.AddDays 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("AddHours")]
    public static RuntimeValue AddHours (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddHours", () => new DotNetVal (Me (self).AddHours (PluginKit.Num (x0, "NDate.AddHours 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("AddMicroseconds")]
    public static RuntimeValue AddMicroseconds (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddMicroseconds", () => new DotNetVal (Me (self).AddMicroseconds (PluginKit.Num (x0, "NDate.AddMicroseconds 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("AddMilliseconds")]
    public static RuntimeValue AddMilliseconds (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddMilliseconds", () => new DotNetVal (Me (self).AddMilliseconds (PluginKit.Num (x0, "NDate.AddMilliseconds 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("AddMinutes")]
    public static RuntimeValue AddMinutes (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddMinutes", () => new DotNetVal (Me (self).AddMinutes (PluginKit.Num (x0, "NDate.AddMinutes 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("AddMonths")]
    public static RuntimeValue AddMonths (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddMonths", () => new DotNetVal (Me (self).AddMonths (PluginKit.Int (x0, "NDate.AddMonths 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("AddSeconds")]
    public static RuntimeValue AddSeconds (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddSeconds", () => new DotNetVal (Me (self).AddSeconds (PluginKit.Num (x0, "NDate.AddSeconds 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("AddTicks")]
    public static RuntimeValue AddTicks (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddTicks", () => new DotNetVal (Me (self).AddTicks (PluginKit.Long (x0, "NDate.AddTicks 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("AddYears")]
    public static RuntimeValue AddYears (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddYears", () => new DotNetVal (Me (self).AddYears (PluginKit.Int (x0, "NDate.AddYears 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("CompareTo")]
    public static RuntimeValue CompareTo (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.CompareTo", () => IntVal.Of (Me (self).CompareTo (PluginKit.ToNet (x0))));

    // 跳过 Deconstruct：值类型上返回 void 的就是**改原地**的方法 ——改的是装箱那份副本，白做

    [ClassMethod("Equals")]
    public static RuntimeValue Equals (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.Equals", () => new BoolVal (Me (self).Equals (PluginKit.ToNet (x0))));

    // 跳过 GetDateTimeFormats：签名  -> String[] 里有映射表没有的类型

    [ClassMethod("GetHashCode")]
    public static RuntimeValue GetHashCode (RuntimeValue self)
        => PluginKit.Guarded ("NDate.GetHashCode", () => IntVal.Of (Me (self).GetHashCode ()));

    // 跳过 GetType：挑中的那个签名是  -> Type，里面有映射表没有的类型（同名 1 个 / 实例 1 个）

    // 跳过 GetTypeCode：挑中的那个签名是  -> TypeCode，里面有映射表没有的类型（同名 1 个 / 实例 1 个）

    [ClassMethod("IsDaylightSavingTime")]
    public static RuntimeValue IsDaylightSavingTime (RuntimeValue self)
        => PluginKit.Guarded ("NDate.IsDaylightSavingTime", () => new BoolVal (Me (self).IsDaylightSavingTime ()));

    // 跳过 Subtract：挑中的那个签名是 DateTime -> TimeSpan，里面有映射表没有的类型（同名 2 个 / 实例 2 个）

    [ClassMethod("ToBinary")]
    public static RuntimeValue ToBinary (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToBinary", () => PluginKit.Narrow (Me (self).ToBinary ()));

    [ClassMethod("ToFileTime")]
    public static RuntimeValue ToFileTime (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToFileTime", () => PluginKit.Narrow (Me (self).ToFileTime ()));

    [ClassMethod("ToFileTimeUtc")]
    public static RuntimeValue ToFileTimeUtc (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToFileTimeUtc", () => PluginKit.Narrow (Me (self).ToFileTimeUtc ()));

    [ClassMethod("ToLocalTime")]
    public static RuntimeValue ToLocalTime (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToLocalTime", () => new DotNetVal (Me (self).ToLocalTime (), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("ToLongDateString")]
    public static RuntimeValue ToLongDateString (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToLongDateString", () => new StringVal (Me (self).ToLongDateString ()));

    [ClassMethod("ToLongTimeString")]
    public static RuntimeValue ToLongTimeString (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToLongTimeString", () => new StringVal (Me (self).ToLongTimeString ()));

    [ClassMethod("ToOADate")]
    public static RuntimeValue ToOADate (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToOADate", () => new RealVal (Me (self).ToOADate ()));

    [ClassMethod("ToShortDateString")]
    public static RuntimeValue ToShortDateString (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToShortDateString", () => new StringVal (Me (self).ToShortDateString ()));

    [ClassMethod("ToShortTimeString")]
    public static RuntimeValue ToShortTimeString (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToShortTimeString", () => new StringVal (Me (self).ToShortTimeString ()));

    [ClassMethod("ToString")]
    public static RuntimeValue ToString (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToString", () => new StringVal (Me (self).ToString ()));

    [ClassMethod("ToUniversalTime")]
    public static RuntimeValue ToUniversalTime (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToUniversalTime", () => new DotNetVal (Me (self).ToUniversalTime (), PluginKit.ClassOf ("DateTime")));

    // 跳过 TryFormat：挑中的那个签名是 Span`1,Int32&,ReadOnlySpan`1,IFormatProvider -> Boolean，里面有映射表没有的类型（同名 2 个 / 实例 2 个）

}