// <auto-generated>
//   由 `Adaptor.CsClass` 生成（`lib/adaptor.rav`）—— 别手改，下次生成会盖掉。
//   要改行为：改那张映射表；要改这一份：把它挪出 Ravel.Generated/ 自己接着写。
//
//   类型 System.DateTime → 模块 NDate / 类 DateTime；成员 Add AddDays AddHours AddMicroseconds AddMilliseconds AddMinutes AddMonths AddSeconds AddTicks AddYears CompareTo Deconstruct Equals GetDateTimeFormats GetHashCode GetType GetTypeCode IsDaylightSavingTime Subtract ToBinary ToFileTime ToFileTimeUtc ToLocalTime ToLongDateString ToLongTimeString ToOADate ToShortDateString ToShortTimeString ToString ToUniversalTime TryFormat
//   属性/字段 Date Day DayOfWeek DayOfYear Hour Kind Microsecond Millisecond Minute Month Nanosecond Second Ticks TimeOfDay Year
//
//   **这是实例那半**：`[ClassCtor]` + `[ClassMethod]` + `[ClassProperty]`，`self` 先脱壳再调。
//   静态成员在另一份里（`Adaptor.Cs`）。
//   属性/字段是**一个名字两个方向**（`sb.Length` / `sb.Length = 2`）—— 走 `by` 那套，
//   不必发明 `SetLength` 那种名字；写不进去的标 `ReadOnly`，并在上面写明理由。
// </auto-generated>

namespace Ravel.Runtime;

[RavelModule("NDate")]
[RavelClass("DateTime", Implements = "IValue")]
internal static class DateTimeAdaptor
{
    private static System.DateTime Me (RuntimeValue self)
        => (System.DateTime)((DotNetVal)self).Value;

    [ClassCtor]
    public static RuntimeValue New (RuntimeValue arg)
        => new DotNetVal (new System.DateTime (PluginKit.Long (arg, "DateTime 的构造器参数")), PluginKit.ClassOf ("DateTime"));

    [ClassProperty("Date", ReadOnly = true)]
    public static RuntimeValue Date (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NDate.Date", () => PluginKit.Wrap (Me (self).Date, "DateTime"));

    [ClassProperty("Day", ReadOnly = true)]
    public static RuntimeValue Day (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NDate.Day", () => IntVal.Of (Me (self).Day));

    [ClassProperty("DayOfWeek", ReadOnly = true)]
    public static RuntimeValue DayOfWeek (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NDate.DayOfWeek", () => PluginKit.Wrap (Me (self).DayOfWeek, "DayOfWeek"));

    [ClassProperty("DayOfYear", ReadOnly = true)]
    public static RuntimeValue DayOfYear (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NDate.DayOfYear", () => IntVal.Of (Me (self).DayOfYear));

    [ClassProperty("Hour", ReadOnly = true)]
    public static RuntimeValue Hour (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NDate.Hour", () => IntVal.Of (Me (self).Hour));

    [ClassProperty("Kind", ReadOnly = true)]
    public static RuntimeValue Kind (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NDate.Kind", () => PluginKit.Wrap (Me (self).Kind, "DateTimeKind"));

    [ClassProperty("Microsecond", ReadOnly = true)]
    public static RuntimeValue Microsecond (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NDate.Microsecond", () => IntVal.Of (Me (self).Microsecond));

    [ClassProperty("Millisecond", ReadOnly = true)]
    public static RuntimeValue Millisecond (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NDate.Millisecond", () => IntVal.Of (Me (self).Millisecond));

    [ClassProperty("Minute", ReadOnly = true)]
    public static RuntimeValue Minute (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NDate.Minute", () => IntVal.Of (Me (self).Minute));

    [ClassProperty("Month", ReadOnly = true)]
    public static RuntimeValue Month (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NDate.Month", () => IntVal.Of (Me (self).Month));

    [ClassProperty("Nanosecond", ReadOnly = true)]
    public static RuntimeValue Nanosecond (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NDate.Nanosecond", () => IntVal.Of (Me (self).Nanosecond));

    [ClassProperty("Second", ReadOnly = true)]
    public static RuntimeValue Second (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NDate.Second", () => IntVal.Of (Me (self).Second));

    [ClassProperty("Ticks", ReadOnly = true)]
    public static RuntimeValue Ticks (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NDate.Ticks", () => PluginKit.Narrow (Me (self).Ticks));

    [ClassProperty("TimeOfDay", ReadOnly = true)]
    public static RuntimeValue TimeOfDay (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NDate.TimeOfDay", () => PluginKit.Wrap (Me (self).TimeOfDay, "TimeSpan"));

    [ClassProperty("Year", ReadOnly = true)]
    public static RuntimeValue Year (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NDate.Year", () => IntVal.Of (Me (self).Year));

    [ClassMethod("Add")]
    public static RuntimeValue Add (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.Add", () => new DotNetVal (Me (self).Add ((System.TimeSpan) PluginKit.ToObject (x0, typeof (System.TimeSpan), "NDate.Add 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("AddDays")]
    public static RuntimeValue AddDays (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddDays", () => new DotNetVal (Me (self).AddDays (PluginKit.Num (x0, "NDate.AddDays 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("AddHours")]
    public static RuntimeValue AddHours (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddHours", () => new DotNetVal (Me (self).AddHours (PluginKit.Num (x0, "NDate.AddHours 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("AddMicroseconds")]
    public static RuntimeValue AddMicroseconds (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddMicroseconds", () => new DotNetVal (Me (self).AddMicroseconds (PluginKit.Num (x0, "NDate.AddMicroseconds 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("AddMilliseconds")]
    public static RuntimeValue AddMilliseconds (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddMilliseconds", () => new DotNetVal (Me (self).AddMilliseconds (PluginKit.Num (x0, "NDate.AddMilliseconds 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("AddMinutes")]
    public static RuntimeValue AddMinutes (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddMinutes", () => new DotNetVal (Me (self).AddMinutes (PluginKit.Num (x0, "NDate.AddMinutes 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("AddMonths")]
    public static RuntimeValue AddMonths (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddMonths", () => new DotNetVal (Me (self).AddMonths (PluginKit.Int (x0, "NDate.AddMonths 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("AddSeconds")]
    public static RuntimeValue AddSeconds (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddSeconds", () => new DotNetVal (Me (self).AddSeconds (PluginKit.Num (x0, "NDate.AddSeconds 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("AddTicks")]
    public static RuntimeValue AddTicks (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddTicks", () => new DotNetVal (Me (self).AddTicks (PluginKit.Long (x0, "NDate.AddTicks 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("AddYears")]
    public static RuntimeValue AddYears (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.AddYears", () => new DotNetVal (Me (self).AddYears (PluginKit.Int (x0, "NDate.AddYears 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("CompareTo")]
    public static RuntimeValue CompareTo (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.CompareTo", () => IntVal.Of (Me (self).CompareTo (PluginKit.ToNet (x0))));
    [ClassMethod("CompareTo_2")]
    public static RuntimeValue CompareTo_2 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.CompareTo", () => IntVal.Of (Me (self).CompareTo ((System.DateTime) PluginKit.ToObject (x0, typeof (System.DateTime), "NDate.CompareTo 的第 1 个实参"))));

    // 跳过 Deconstruct：值类型上返回 void 的就是**改原地**的方法 ——改的是装箱那份副本，白做

    [ClassMethod("Equals")]
    public static RuntimeValue Equals (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.Equals", () => new BoolVal (Me (self).Equals (PluginKit.ToNet (x0))));
    [ClassMethod("Equals_2")]
    public static RuntimeValue Equals_2 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.Equals", () => new BoolVal (Me (self).Equals ((System.DateTime) PluginKit.ToObject (x0, typeof (System.DateTime), "NDate.Equals 的第 1 个实参"))));

    [ClassMethod("GetDateTimeFormats")]
    public static RuntimeValue GetDateTimeFormats (RuntimeValue self)
        => PluginKit.Guarded ("NDate.GetDateTimeFormats", () => PluginKit.ToRavel (Me (self).GetDateTimeFormats ()));
    [ClassMethod("GetDateTimeFormats_2")]
    public static RuntimeValue GetDateTimeFormats_2 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.GetDateTimeFormats", () => PluginKit.ToRavel (Me (self).GetDateTimeFormats (PluginKit.Char (x0, "NDate.GetDateTimeFormats 的第 1 个实参"))));
    [ClassMethod("GetDateTimeFormats_3")]
    public static RuntimeValue GetDateTimeFormats_3 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.GetDateTimeFormats", () => PluginKit.ToRavel (Me (self).GetDateTimeFormats ((System.IFormatProvider) PluginKit.ToObject (x0, typeof (System.IFormatProvider), "NDate.GetDateTimeFormats 的第 1 个实参"))));
    [ClassMethod("GetDateTimeFormats_4")]
    public static RuntimeValue GetDateTimeFormats_4 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NDate.GetDateTimeFormats", () => PluginKit.ToRavel (Me (self).GetDateTimeFormats (PluginKit.Char (x0, "NDate.GetDateTimeFormats 的第 1 个实参"), (System.IFormatProvider) PluginKit.ToObject (x1, typeof (System.IFormatProvider), "NDate.GetDateTimeFormats 的第 2 个实参"))));

    [ClassMethod("GetHashCode")]
    public static RuntimeValue GetHashCode (RuntimeValue self)
        => PluginKit.Guarded ("NDate.GetHashCode", () => IntVal.Of (Me (self).GetHashCode ()));

    [ClassMethod("GetType")]
    public static RuntimeValue GetType (RuntimeValue self)
        => PluginKit.Guarded ("NDate.GetType", () => PluginKit.Wrap (Me (self).GetType (), "Type"));

    [ClassMethod("GetTypeCode")]
    public static RuntimeValue GetTypeCode (RuntimeValue self)
        => PluginKit.Guarded ("NDate.GetTypeCode", () => PluginKit.Wrap (Me (self).GetTypeCode (), "TypeCode"));

    [ClassMethod("IsDaylightSavingTime")]
    public static RuntimeValue IsDaylightSavingTime (RuntimeValue self)
        => PluginKit.Guarded ("NDate.IsDaylightSavingTime", () => new BoolVal (Me (self).IsDaylightSavingTime ()));

    [ClassMethod("Subtract")]
    public static RuntimeValue Subtract (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.Subtract", () => PluginKit.Wrap (Me (self).Subtract ((System.DateTime) PluginKit.ToObject (x0, typeof (System.DateTime), "NDate.Subtract 的第 1 个实参")), "TimeSpan"));
    [ClassMethod("Subtract_2")]
    public static RuntimeValue Subtract_2 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.Subtract", () => new DotNetVal (Me (self).Subtract ((System.TimeSpan) PluginKit.ToObject (x0, typeof (System.TimeSpan), "NDate.Subtract 的第 1 个实参")), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("ToBinary")]
    public static RuntimeValue ToBinary (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToBinary", () => PluginKit.Narrow (Me (self).ToBinary ()));

    [ClassMethod("ToFileTime")]
    public static RuntimeValue ToFileTime (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToFileTime", () => PluginKit.Narrow (Me (self).ToFileTime ()));

    [ClassMethod("ToFileTimeUtc")]
    public static RuntimeValue ToFileTimeUtc (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToFileTimeUtc", () => PluginKit.Narrow (Me (self).ToFileTimeUtc ()));

    [ClassMethod("ToLocalTime")]
    public static RuntimeValue ToLocalTime (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToLocalTime", () => new DotNetVal (Me (self).ToLocalTime (), PluginKit.ClassOf ("DateTime")));

    [ClassMethod("ToLongDateString")]
    public static RuntimeValue ToLongDateString (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToLongDateString", () => new StringVal (Me (self).ToLongDateString ()));

    [ClassMethod("ToLongTimeString")]
    public static RuntimeValue ToLongTimeString (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToLongTimeString", () => new StringVal (Me (self).ToLongTimeString ()));

    [ClassMethod("ToOADate")]
    public static RuntimeValue ToOADate (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToOADate", () => new RealVal (Me (self).ToOADate ()));

    [ClassMethod("ToShortDateString")]
    public static RuntimeValue ToShortDateString (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToShortDateString", () => new StringVal (Me (self).ToShortDateString ()));

    [ClassMethod("ToShortTimeString")]
    public static RuntimeValue ToShortTimeString (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToShortTimeString", () => new StringVal (Me (self).ToShortTimeString ()));

    [ClassMethod("ToString")]
    public static RuntimeValue ToString (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToString", () => new StringVal (Me (self).ToString ()));
    [ClassMethod("ToString_2")]
    public static RuntimeValue ToString_2 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.ToString", () => new StringVal (Me (self).ToString (PluginKit.Text (x0, "NDate.ToString 的第 1 个实参").Value)));
    [ClassMethod("ToString_3")]
    public static RuntimeValue ToString_3 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NDate.ToString", () => new StringVal (Me (self).ToString ((System.IFormatProvider) PluginKit.ToObject (x0, typeof (System.IFormatProvider), "NDate.ToString 的第 1 个实参"))));
    [ClassMethod("ToString_4")]
    public static RuntimeValue ToString_4 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NDate.ToString", () => new StringVal (Me (self).ToString (PluginKit.Text (x0, "NDate.ToString 的第 1 个实参").Value, (System.IFormatProvider) PluginKit.ToObject (x1, typeof (System.IFormatProvider), "NDate.ToString 的第 2 个实参"))));

    [ClassMethod("ToUniversalTime")]
    public static RuntimeValue ToUniversalTime (RuntimeValue self)
        => PluginKit.Guarded ("NDate.ToUniversalTime", () => new DotNetVal (Me (self).ToUniversalTime (), PluginKit.ClassOf ("DateTime")));

    // 跳过 TryFormat：值类型上返回 void 的就是**改原地**的方法 ——改的是装箱那份副本，白做

}