// <auto-generated>
//   由 `tools/mkadaptor.rav` 生成 —— 别手改，下次生成会盖掉。
//   要改行为：改生成器；要改这一份：把它挪出 Ravel.Generated/ 自己接着写。
//
//   源：`dotnet out/ravel.dll tools/mkadaptor.rav System.Math NMath Max Min Abs Sign Clamp Sqrt`
// </auto-generated>

namespace Ravel.Runtime;

[RavelModule("NMath")]
internal static class NMathAdaptor
{
    [RavelFn("Max")]
    public static RuntimeValue Max (RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NMath.Max", () => IntVal.Of ((System.Math.Max (PluginKit.Int (x0, "NMath.Max 的第 1 个实参"), PluginKit.Int (x1, "NMath.Max 的第 2 个实参")))));

    [RavelFn("Min")]
    public static RuntimeValue Min (RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NMath.Min", () => IntVal.Of ((System.Math.Min (PluginKit.Int (x0, "NMath.Min 的第 1 个实参"), PluginKit.Int (x1, "NMath.Min 的第 2 个实参")))));

    [RavelFn("Abs")]
    public static RuntimeValue Abs (RuntimeValue x0)
        => PluginKit.Guarded ("NMath.Abs", () => IntVal.Of ((System.Math.Abs (PluginKit.Int (x0, "NMath.Abs 的第 1 个实参")))));

    [RavelFn("Sign")]
    public static RuntimeValue Sign (RuntimeValue x0)
        => PluginKit.Guarded ("NMath.Sign", () => IntVal.Of ((System.Math.Sign (PluginKit.Int (x0, "NMath.Sign 的第 1 个实参")))));

    [RavelFn("Clamp")]
    public static RuntimeValue Clamp (RuntimeValue x0, RuntimeValue x1, RuntimeValue x2)
        => PluginKit.Guarded ("NMath.Clamp", () => IntVal.Of ((System.Math.Clamp (PluginKit.Int (x0, "NMath.Clamp 的第 1 个实参"), PluginKit.Int (x1, "NMath.Clamp 的第 2 个实参"), PluginKit.Int (x2, "NMath.Clamp 的第 3 个实参")))));

    // 跳过 Sqrt：没有能映射的重载（同名静态方法 1 个，0 个类型认得出，1 个被筛掉）

}