// <auto-generated>
//   由 `Adaptor.CsClass` 生成（`lib/adaptor.rav`）—— 别手改，下次生成会盖掉。
//   要改行为：改那张映射表；要改这一份：把它挪出 Ravel.Generated/ 自己接着写。
//
//   类型 System.Text.StringBuilder → 模块 NSb / 类 StringBuilder；成员 Append AppendFormat AppendJoin AppendLine Clear CopyTo EnsureCapacity Equals GetChunks GetHashCode GetType Insert Remove Replace ToString
//   属性 Capacity Length MaxCapacity
//
//   **这是实例那半**：`[ClassCtor]` + `[ClassMethod]` + `[ClassProperty]`，`self` 先脱壳再调。
//   静态成员在另一份里（`Adaptor.Cs`）。
//   属性是**一个名字两个方向**（`sb.Length` / `sb.Length = 2`）—— 走 `by` 那套，
//   不必发明 `SetLength` 那种名字；没有 setter 的标 `ReadOnly`，写由引擎在槽上拦。
// </auto-generated>

namespace Ravel.Runtime;

[RavelModule("NSb")]
[RavelClass("StringBuilder")]
internal static class StringBuilderAdaptor
{
    private static System.Text.StringBuilder Me (RuntimeValue self)
        => (System.Text.StringBuilder)((DotNetVal)self).Value;

    [ClassCtor]
    public static RuntimeValue New (RuntimeValue arg)
        => arg is VoidVal
            ? new DotNetVal (new System.Text.StringBuilder (), PluginKit.ClassOf ("StringBuilder"))
            : throw PluginKit.Fail ("System.Text.StringBuilder 的 .NET 构造器是 0 个参数的 —— 像 `类 ()` 那样调，别给实参", ErrorKind.Argument);

    [ClassProperty("Capacity")]
    public static RuntimeValue Capacity (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NSb.Capacity", () =>
        {
            if (arg is VoidVal) return IntVal.Of (Me (self).Capacity);
            Me (self).Capacity = PluginKit.Int (arg, "NSb.Capacity");
            return PluginKit.Void;
        });

    [ClassProperty("Length")]
    public static RuntimeValue Length (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NSb.Length", () =>
        {
            if (arg is VoidVal) return IntVal.Of (Me (self).Length);
            Me (self).Length = PluginKit.Int (arg, "NSb.Length");
            return PluginKit.Void;
        });

    [ClassProperty("MaxCapacity", ReadOnly = true)]
    public static RuntimeValue MaxCapacity (RuntimeValue self, RuntimeValue arg)
        => PluginKit.Guarded ("NSb.MaxCapacity", () => IntVal.Of (Me (self).MaxCapacity));

    [ClassMethod("Append")]
    public static RuntimeValue Append (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append (PluginKit.Int (x0, "NSb.Append 的第 1 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_2")]
    public static RuntimeValue Append_2 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append (PluginKit.Long (x0, "NSb.Append 的第 1 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_3")]
    public static RuntimeValue Append_3 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append (PluginKit.Text (x0, "NSb.Append 的第 1 个实参").Value), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_4")]
    public static RuntimeValue Append_4 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append (PluginKit.Bool (x0, "NSb.Append 的第 1 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_5")]
    public static RuntimeValue Append_5 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append (PluginKit.Char (x0, "NSb.Append 的第 1 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_6")]
    public static RuntimeValue Append_6 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append (PluginKit.Num (x0, "NSb.Append 的第 1 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_7")]
    public static RuntimeValue Append_7 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append ((float)PluginKit.Num (x0, "NSb.Append 的第 1 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_8")]
    public static RuntimeValue Append_8 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append (PluginKit.Char (x0, "NSb.Append 的第 1 个实参"), PluginKit.Int (x1, "NSb.Append 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_9")]
    public static RuntimeValue Append_9 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append (PluginKit.Chars (x0, "NSb.Append 的第 1 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_10")]
    public static RuntimeValue Append_10 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append (PluginKit.ToNet (x0)), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_11")]
    public static RuntimeValue Append_11 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append ((System.Byte) PluginKit.ToObject (x0, typeof (System.Byte), "NSb.Append 的第 1 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_12")]
    public static RuntimeValue Append_12 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append ((System.Decimal) PluginKit.ToObject (x0, typeof (System.Decimal), "NSb.Append 的第 1 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_13")]
    public static RuntimeValue Append_13 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append ((System.Int16) PluginKit.ToObject (x0, typeof (System.Int16), "NSb.Append 的第 1 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_14")]
    public static RuntimeValue Append_14 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append ((System.ReadOnlyMemory<System.Char>) PluginKit.ToObject (x0, typeof (System.ReadOnlyMemory<System.Char>), "NSb.Append 的第 1 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_15")]
    public static RuntimeValue Append_15 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append ((System.SByte) PluginKit.ToObject (x0, typeof (System.SByte), "NSb.Append 的第 1 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_16")]
    public static RuntimeValue Append_16 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append ((System.Text.StringBuilder) PluginKit.ToObject (x0, typeof (System.Text.StringBuilder), "NSb.Append 的第 1 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_17")]
    public static RuntimeValue Append_17 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append ((System.UInt16) PluginKit.ToObject (x0, typeof (System.UInt16), "NSb.Append 的第 1 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_18")]
    public static RuntimeValue Append_18 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append ((System.UInt32) PluginKit.ToObject (x0, typeof (System.UInt32), "NSb.Append 的第 1 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Append_19")]
    public static RuntimeValue Append_19 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Append", () => new DotNetVal (Me (self).Append ((System.UInt64) PluginKit.ToObject (x0, typeof (System.UInt64), "NSb.Append 的第 1 个实参")), PluginKit.ClassOf ("StringBuilder")));

    [ClassMethod("AppendFormat")]
    public static RuntimeValue AppendFormat (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.AppendFormat", () => new DotNetVal (Me (self).AppendFormat (PluginKit.Text (x0, "NSb.AppendFormat 的第 1 个实参").Value, PluginKit.ToNet (x1)), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("AppendFormat_2")]
    public static RuntimeValue AppendFormat_2 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.AppendFormat", () => new DotNetVal (Me (self).AppendFormat (PluginKit.Text (x0, "NSb.AppendFormat 的第 1 个实参").Value, (System.Object[]) PluginKit.ToObject (x1, typeof (System.Object[]), "NSb.AppendFormat 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));

    [ClassMethod("AppendJoin")]
    public static RuntimeValue AppendJoin (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.AppendJoin", () => new DotNetVal (Me (self).AppendJoin (PluginKit.Text (x0, "NSb.AppendJoin 的第 1 个实参").Value, PluginKit.Strs (x1, "NSb.AppendJoin 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("AppendJoin_2")]
    public static RuntimeValue AppendJoin_2 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.AppendJoin", () => new DotNetVal (Me (self).AppendJoin (PluginKit.Text (x0, "NSb.AppendJoin 的第 1 个实参").Value, (System.Object[]) PluginKit.ToObject (x1, typeof (System.Object[]), "NSb.AppendJoin 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("AppendJoin_3")]
    public static RuntimeValue AppendJoin_3 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.AppendJoin", () => new DotNetVal (Me (self).AppendJoin (PluginKit.Char (x0, "NSb.AppendJoin 的第 1 个实参"), PluginKit.Strs (x1, "NSb.AppendJoin 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("AppendJoin_4")]
    public static RuntimeValue AppendJoin_4 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.AppendJoin", () => new DotNetVal (Me (self).AppendJoin (PluginKit.Char (x0, "NSb.AppendJoin 的第 1 个实参"), (System.Object[]) PluginKit.ToObject (x1, typeof (System.Object[]), "NSb.AppendJoin 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));

    [ClassMethod("AppendLine")]
    public static RuntimeValue AppendLine (RuntimeValue self)
        => PluginKit.Guarded ("NSb.AppendLine", () => new DotNetVal (Me (self).AppendLine (), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("AppendLine_2")]
    public static RuntimeValue AppendLine_2 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.AppendLine", () => new DotNetVal (Me (self).AppendLine (PluginKit.Text (x0, "NSb.AppendLine 的第 1 个实参").Value), PluginKit.ClassOf ("StringBuilder")));

    [ClassMethod("Clear")]
    public static RuntimeValue Clear (RuntimeValue self)
        => PluginKit.Guarded ("NSb.Clear", () => new DotNetVal (Me (self).Clear (), PluginKit.ClassOf ("StringBuilder")));

    // 跳过 CopyTo：没有能生成的实例重载（同名方法 2 个，实例 2 个）

    [ClassMethod("EnsureCapacity")]
    public static RuntimeValue EnsureCapacity (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.EnsureCapacity", () => IntVal.Of (Me (self).EnsureCapacity (PluginKit.Int (x0, "NSb.EnsureCapacity 的第 1 个实参"))));

    [ClassMethod("Equals")]
    public static RuntimeValue Equals (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Equals", () => new BoolVal (Me (self).Equals (PluginKit.ToNet (x0))));
    [ClassMethod("Equals_2")]
    public static RuntimeValue Equals_2 (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSb.Equals", () => new BoolVal (Me (self).Equals ((System.Text.StringBuilder) PluginKit.ToObject (x0, typeof (System.Text.StringBuilder), "NSb.Equals 的第 1 个实参"))));

    [ClassMethod("GetChunks")]
    public static RuntimeValue GetChunks (RuntimeValue self)
        => PluginKit.Guarded ("NSb.GetChunks", () => PluginKit.Wrap (Me (self).GetChunks (), "ChunkEnumerator"));

    [ClassMethod("GetHashCode")]
    public static RuntimeValue GetHashCode (RuntimeValue self)
        => PluginKit.Guarded ("NSb.GetHashCode", () => IntVal.Of (Me (self).GetHashCode ()));

    [ClassMethod("GetType")]
    public static RuntimeValue GetType (RuntimeValue self)
        => PluginKit.Guarded ("NSb.GetType", () => PluginKit.Wrap (Me (self).GetType (), "Type"));

    [ClassMethod("Insert")]
    public static RuntimeValue Insert (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Insert", () => new DotNetVal (Me (self).Insert (PluginKit.Int (x0, "NSb.Insert 的第 1 个实参"), PluginKit.Int (x1, "NSb.Insert 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Insert_2")]
    public static RuntimeValue Insert_2 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Insert", () => new DotNetVal (Me (self).Insert (PluginKit.Int (x0, "NSb.Insert 的第 1 个实参"), PluginKit.Long (x1, "NSb.Insert 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Insert_3")]
    public static RuntimeValue Insert_3 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Insert", () => new DotNetVal (Me (self).Insert (PluginKit.Int (x0, "NSb.Insert 的第 1 个实参"), PluginKit.Text (x1, "NSb.Insert 的第 2 个实参").Value), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Insert_4")]
    public static RuntimeValue Insert_4 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Insert", () => new DotNetVal (Me (self).Insert (PluginKit.Int (x0, "NSb.Insert 的第 1 个实参"), PluginKit.Bool (x1, "NSb.Insert 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Insert_5")]
    public static RuntimeValue Insert_5 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Insert", () => new DotNetVal (Me (self).Insert (PluginKit.Int (x0, "NSb.Insert 的第 1 个实参"), PluginKit.Char (x1, "NSb.Insert 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Insert_6")]
    public static RuntimeValue Insert_6 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Insert", () => new DotNetVal (Me (self).Insert (PluginKit.Int (x0, "NSb.Insert 的第 1 个实参"), PluginKit.Num (x1, "NSb.Insert 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Insert_7")]
    public static RuntimeValue Insert_7 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Insert", () => new DotNetVal (Me (self).Insert (PluginKit.Int (x0, "NSb.Insert 的第 1 个实参"), (float)PluginKit.Num (x1, "NSb.Insert 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Insert_8")]
    public static RuntimeValue Insert_8 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Insert", () => new DotNetVal (Me (self).Insert (PluginKit.Int (x0, "NSb.Insert 的第 1 个实参"), PluginKit.Chars (x1, "NSb.Insert 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Insert_9")]
    public static RuntimeValue Insert_9 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Insert", () => new DotNetVal (Me (self).Insert (PluginKit.Int (x0, "NSb.Insert 的第 1 个实参"), PluginKit.ToNet (x1)), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Insert_10")]
    public static RuntimeValue Insert_10 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Insert", () => new DotNetVal (Me (self).Insert (PluginKit.Int (x0, "NSb.Insert 的第 1 个实参"), (System.Byte) PluginKit.ToObject (x1, typeof (System.Byte), "NSb.Insert 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Insert_11")]
    public static RuntimeValue Insert_11 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Insert", () => new DotNetVal (Me (self).Insert (PluginKit.Int (x0, "NSb.Insert 的第 1 个实参"), (System.Decimal) PluginKit.ToObject (x1, typeof (System.Decimal), "NSb.Insert 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Insert_12")]
    public static RuntimeValue Insert_12 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Insert", () => new DotNetVal (Me (self).Insert (PluginKit.Int (x0, "NSb.Insert 的第 1 个实参"), (System.Int16) PluginKit.ToObject (x1, typeof (System.Int16), "NSb.Insert 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Insert_13")]
    public static RuntimeValue Insert_13 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Insert", () => new DotNetVal (Me (self).Insert (PluginKit.Int (x0, "NSb.Insert 的第 1 个实参"), (System.SByte) PluginKit.ToObject (x1, typeof (System.SByte), "NSb.Insert 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Insert_14")]
    public static RuntimeValue Insert_14 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Insert", () => new DotNetVal (Me (self).Insert (PluginKit.Int (x0, "NSb.Insert 的第 1 个实参"), (System.UInt16) PluginKit.ToObject (x1, typeof (System.UInt16), "NSb.Insert 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Insert_15")]
    public static RuntimeValue Insert_15 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Insert", () => new DotNetVal (Me (self).Insert (PluginKit.Int (x0, "NSb.Insert 的第 1 个实参"), (System.UInt32) PluginKit.ToObject (x1, typeof (System.UInt32), "NSb.Insert 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Insert_16")]
    public static RuntimeValue Insert_16 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Insert", () => new DotNetVal (Me (self).Insert (PluginKit.Int (x0, "NSb.Insert 的第 1 个实参"), (System.UInt64) PluginKit.ToObject (x1, typeof (System.UInt64), "NSb.Insert 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));

    [ClassMethod("Remove")]
    public static RuntimeValue Remove (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Remove", () => new DotNetVal (Me (self).Remove (PluginKit.Int (x0, "NSb.Remove 的第 1 个实参"), PluginKit.Int (x1, "NSb.Remove 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));

    [ClassMethod("Replace")]
    public static RuntimeValue Replace (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Replace", () => new DotNetVal (Me (self).Replace (PluginKit.Text (x0, "NSb.Replace 的第 1 个实参").Value, PluginKit.Text (x1, "NSb.Replace 的第 2 个实参").Value), PluginKit.ClassOf ("StringBuilder")));
    [ClassMethod("Replace_2")]
    public static RuntimeValue Replace_2 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.Replace", () => new DotNetVal (Me (self).Replace (PluginKit.Char (x0, "NSb.Replace 的第 1 个实参"), PluginKit.Char (x1, "NSb.Replace 的第 2 个实参")), PluginKit.ClassOf ("StringBuilder")));

    [ClassMethod("ToString")]
    public static RuntimeValue ToString (RuntimeValue self)
        => PluginKit.Guarded ("NSb.ToString", () => new StringVal (Me (self).ToString ()));
    [ClassMethod("ToString_2")]
    public static RuntimeValue ToString_2 (RuntimeValue self, RuntimeValue x0, RuntimeValue x1)
        => PluginKit.Guarded ("NSb.ToString", () => new StringVal (Me (self).ToString (PluginKit.Int (x0, "NSb.ToString 的第 1 个实参"), PluginKit.Int (x1, "NSb.ToString 的第 2 个实参"))));

}