// <auto-generated>
//   由 `Adaptor.CsClass` 生成（`lib/adaptor.rav`）—— 别手改，下次生成会盖掉。
//   要改行为：改那张映射表；要改这一份：把它挪出 Ravel.Generated/ 自己接着写。
//
//   类型 System.TimeSpan → 模块 NSpan / 类 TimeSpan；成员 Add CompareTo Divide Duration Equals GetHashCode GetType Multiply Negate Subtract ToString TryFormat
//
//   **这是实例那半**：`[ClassCtor]` + `[ClassMethod]`，`self` 先脱壳再调。
//   静态成员在另一份里（`Adaptor.Cs`）。**属性访问器（`get_X` / `set_X`）这一版不做。**
// </auto-generated>

namespace Ravel.Runtime;

[RavelModule("NSpan")]
[RavelClass("TimeSpan", Implements = "IValue")]
internal static class TimeSpanAdaptor
{
    private static System.TimeSpan Me (RuntimeValue self)
        => (System.TimeSpan)((DotNetVal)self).Value;

    [ClassCtor]
    public static RuntimeValue New (RuntimeValue arg)
        => new DotNetVal (new System.TimeSpan (PluginKit.Long (arg, "TimeSpan 的构造器参数")), PluginKit.ClassOf ("TimeSpan"));

    [ClassMethod("Add")]
    public static RuntimeValue Add (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSpan.Add", () => new DotNetVal (Me (self).Add ((System.TimeSpan) PluginKit.ToObject (x0, typeof (System.TimeSpan), "NSpan.Add 的第 1 个实参")), PluginKit.ClassOf ("TimeSpan")));

    [ClassMethod("CompareTo")]
    public static RuntimeValue CompareTo (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSpan.CompareTo", () => IntVal.Of (Me (self).CompareTo (PluginKit.ToNet (x0))));

    [ClassMethod("Divide")]
    public static RuntimeValue Divide (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSpan.Divide", () => new DotNetVal (Me (self).Divide (PluginKit.Num (x0, "NSpan.Divide 的第 1 个实参")), PluginKit.ClassOf ("TimeSpan")));

    [ClassMethod("Duration")]
    public static RuntimeValue Duration (RuntimeValue self)
        => PluginKit.Guarded ("NSpan.Duration", () => new DotNetVal (Me (self).Duration (), PluginKit.ClassOf ("TimeSpan")));

    [ClassMethod("Equals")]
    public static RuntimeValue Equals (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSpan.Equals", () => new BoolVal (Me (self).Equals (PluginKit.ToNet (x0))));

    [ClassMethod("GetHashCode")]
    public static RuntimeValue GetHashCode (RuntimeValue self)
        => PluginKit.Guarded ("NSpan.GetHashCode", () => IntVal.Of (Me (self).GetHashCode ()));

    [ClassMethod("GetType")]
    public static RuntimeValue GetType (RuntimeValue self)
        => PluginKit.Guarded ("NSpan.GetType", () => PluginKit.Wrap (Me (self).GetType (), "Type"));

    [ClassMethod("Multiply")]
    public static RuntimeValue Multiply (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSpan.Multiply", () => new DotNetVal (Me (self).Multiply (PluginKit.Num (x0, "NSpan.Multiply 的第 1 个实参")), PluginKit.ClassOf ("TimeSpan")));

    [ClassMethod("Negate")]
    public static RuntimeValue Negate (RuntimeValue self)
        => PluginKit.Guarded ("NSpan.Negate", () => new DotNetVal (Me (self).Negate (), PluginKit.ClassOf ("TimeSpan")));

    [ClassMethod("Subtract")]
    public static RuntimeValue Subtract (RuntimeValue self, RuntimeValue x0)
        => PluginKit.Guarded ("NSpan.Subtract", () => new DotNetVal (Me (self).Subtract ((System.TimeSpan) PluginKit.ToObject (x0, typeof (System.TimeSpan), "NSpan.Subtract 的第 1 个实参")), PluginKit.ClassOf ("TimeSpan")));

    [ClassMethod("ToString")]
    public static RuntimeValue ToString (RuntimeValue self)
        => PluginKit.Guarded ("NSpan.ToString", () => new StringVal (Me (self).ToString ()));

    // 跳过 TryFormat：挑中的那个签名是 Span`1,Int32&,ReadOnlySpan`1,IFormatProvider -> Boolean，有进不了生成代码的类型（`ref struct` / `ref` / 泛型参数 —— `typeof` 都写不出来）（同名 2 个 / 实例 2 个）

}